### ISSUE TITLE
Redirect Loop ...

### ISSUE THREAD

**Issue by shailesh91** [assertchris-tutorials/laravel-4-acl#3]
Hello Chris,

I am having a small problem with the tutorial on medium. When I am logged in I get into a redirect loop for every route. Can you tell me any specific reason in this filter.

Route::filter("auth", function(){
    if (Auth::guest()){
        return Redirect::route("user/login");
    }else{
        /\* specifically this part*/
        foreach (Auth::user()->groups as $group){
            foreach ($group->resources as $resource){
                if ($resource->pattern == Route::getCurrentRoute()->getPath()){
                    return;
                }
            }
        }
        return Redirect::route("user/login");
    }
}); 

Looking for your quick reply.

Thanks

**Comment by Rufflesaurus** [comment]
I was following this tutorial and ran into the redirect loop problem. How do you use the allowed() function? Which links should I wrap with it? It's not shown in the tutorial.

Can you please explain that part with an example? A little bit of help would be great! 

By the way, amazing examples, I've learned a lot! 

Thanks in advance!
